server:
 port: '80'

spring:
 security:
  oauth2:
   client:
    registration:
     kakao:
      client-id: e3d5af4bc7278e800a466a3d17d6a38b
      client-secret: NmHigPqlaGgTHLZ9shAQORnWFonZHiLQ
      redirect-uri: http://localhost:80/login/oauth2/code/kakao
      client-authentication-method: client_secret_post
      authorization-grant-type: authorization_code
      scope: account_email #동의 항목
      client-name: Kakao
    provider:
     kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id
 datasource: 
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:xe
  password: tiger
  username: c##project
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  enabled: true
  check-template-location: true
 
 jpa:
  hibernate:
   ddl-auto: none
  generate-ddl: false
  show-sql: true
  database: oracle
  database-platform: org.hibernate.dialect.OracleDialect
 mvc:
  static-path-pattern: /static/**
 devtools:
  livereload:
   enabled: true
logging:
 level:
  org:
   hibernate: info
   
mybatis:
  mapper-locations: classpath:mappers/*.xml